spring:
  application:
    name: FoodApplication
  datasource:
    url: jdbc:mysql://localhost:3306/application?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update    # or validate / create / create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
mail:
  host: https://smtp.gmail.com
  port: 5761
